CREATE DATABASE IF NOT EXISTS api;

USE api;

CREATE TABLE IF NOT EXISTS posts(
id VARCHAR(255) NOT NULL,
title VARCHAR(255) NOT NULL,
slug VARCHAR(255) NOT NULL,
content VARCHAR(255) NOT NULL,
thumbnail LONGBLOB NOT NULL,
author VARCHAR(255) NOT NULL,
posted_at DATETIME NOT NULL,
PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS categories(
id VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL,
description TEXT,
PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS posts_categories(
id_post VARCHAR(255) NOT NULL,
id_category VARCHAR(255) NOT NULL,
PRIMARY KEY(id_post, id_category),
FOREIGN KEY(id_post) REFERENCES posts(id),
FOREIGN KEY(id_category) REFERENCES categories(id)
);